export const EXTENSION_CAPTURE_MESSAGE_TYPE = 'SHOPEE_PRICE_TRACKER_CAPTURE';
export const EXTENSION_COLLECTION_STATUS_MESSAGE_TYPE = 'SHOPEE_PRICE_TRACKER_COLLECTION_STATUS';
export const EXTENSION_CAPTURE_KINDS = Object.freeze({
  PRODUCT_DETAIL: 'product_detail',
  SELECTED_VARIATION: 'selected_variation',
});

export const EXTENSION_COLLECTION_STATUS_CODES = Object.freeze({
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  RATE_LIMITED: 'RATE_LIMITED',
});
